Does echoing error put GHA error in log?

diff --git a/.github/workflows/test.yml b/.github/workflows/test.yml
--- a/.github/workflows/test.yml
+++ b/.github/workflows/test.yml
@@ -26,6 +26,9 @@ jobs:
     name: 'Am I crazy?'
     runs-on: ubuntu-latest
     steps:
+      - name: 'WTF?'
+        run: echo "[ERROR] Umm, wtf?" >&2
+
       - name: 'Fail'
         run: exit 1
 
